<?php

namespace RdvBundle\Repository;

/**
 * FermetureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FermetureRepository extends \Doctrine\ORM\EntityRepository
{
}
