<?php

namespace RdvBundle\Repository;

/**
 * LieuRdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRdvRepository extends \Doctrine\ORM\EntityRepository
{
}
