rdv_homepage:
    path:     /
    defaults: { _controller: RdvBundle:Default:index }
    
rdv_user_profile:
    path:     /profile
    defaults: { _controller: RdvBundle:Default:userProfile } 
        
type_rdv_update:
    path:     /typerdv/update/{id}
    defaults: { _controller: RdvBundle:Default:typeRdvAddUpdate, id:null }
    
type_rdv_delete:
    path:     /typerdv/delete/{id}
    defaults: { _controller: RdvBundle:Default:typeRdvDelete, id:null }
    
rdv_validation_admin:
    path: /validation_admin
    path: /admin/validation_admin
    defaults: { _controller: RdvBundle:ValidationAdmin:index }
 
rdv_validation_pro:
    path:      /validation_pro/{id}
    path:      /admin/validation_pro/{id}
    controller: RdvBundle:ValidationAdmin:validation
    requirements:
        id: '\d+'
    options:
        expose: true

rdv_listing_pro:
    path: /listing_pro
    defaults: { _controller: RdvBundle:Default:ListingPro }
         
rdv_user_list_pro:
    path:      /rdv_user_list
    controller: RdvBundle:Default:UserRdv

user_pro_list:
    path:      /user_pro_list
    controller: RdvBundle:UserProList:index
    
rdv_pro_profile:
    path:      /rdv_pro_profile
    controller: RdvBundle:Default:proProfile

add_lieu_rdv:
    path: /add/lieurdv
    controller: RdvBundle:Default:addLieuRdv
    
create_planning_default:
    path: /create_planning_default
    controller: RdvBundle:Planning:createDefault

pagePerso:
    path:     /pagePerso/{id}
    defaults: { _controller: RdvBundle:Default:pagePerso , id:null }
    requirements:
        id: '\d+'
    options:
        expose: true
    
pagePerso_update:
    path:     /pagePerso/update/{id}
    defaults: { _controller: RdvBundle:Default:pagePersoAddUpdate, id:null }
    
pagePerso_delete:
    path:     /pagePerso/delete/{id}
    defaults: { _controller: RdvBundle:Default:pagePersoDelete, id:null }
    
lieu_rdv_update:
    path:     /lieurdv/update/{id}
    defaults: { _controller: RdvBundle:Default:lieuRdvAddUpdate, id:null }
    
lieu_rdv_delete:
    path:     /lieurdv/delete/{id}
    defaults: { _controller: RdvBundle:Default:lieuRdvDelete, id:null }
    
add_rdv_pro:
    path: /add/rdv/{id}
    defaults: { _controller: RdvBundle:Default:addRdvPro, id:null }