rdv_homepage:
    path:     /
    defaults: { _controller: RdvBundle:Default:index }

rdv_validation_admin:
    path: /admin/validation_admin
    defaults: { _controller: RdvBundle:ValidationAdmin:index }

rdv_validation_pro:
    path:      /admin/validation_pro/{id}
    controller: RdvBundle:ValidationAdmin:validation
    requirements:
        page: '\d+'
    options:
        expose: true

rdv_listing_pro:
    path: /listing_pro
    defaults: { _controller: RdvBundle:ListingPro:index }