rdv_homepage:
    path:     /
    defaults: { _controller: RdvBundle:Default:index }
    
rdv_user_profile:
    path:     /profile
    defaults: { _controller: RdvBundle:Default:userProfile } 
    
rdv_type_rdv:
    path:     /typerdv
    defaults: { _controller: RdvBundle:Default:typeRdv } 
    
rdv_type_rdv_update:
    path:     /typerdv/update/{id}
    defaults: { _controller: RdvBundle:Default:typeRdvAddUpdate, id:null } 