services:
    rdv.datatable.user:
        class: RdvBundle\Datatables\UserDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.user_rdv_list:
        class: RdvBundle\Datatables\UserRdvDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.pro_rdv_list:
        class: RdvBundle\Datatables\ProRdvDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.user_pro_datatable:
        class: RdvBundle\Datatables\UserProDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.typerdv:
        class: RdvBundle\Datatables\TypeRdvDatatable
        parent: sg_datatables.datatable.abstract
        
    app.datatable.fermeture:
        class: RdvBundle\Datatables\FermetureDatatable
        parent: sg_datatables.datatable.abstract